namespace Nvidia.Nvml
{
    public enum NvmlMemoryLocation
    {
        NVML_MEMORY_LOCATION_L1_CACHE = 0,
        NVML_MEMORY_LOCATION_L2_CACHE = 1,
        NVML_MEMORY_LOCATION_DRAM = 2,
        NVML_MEMORY_LOCATION_DEVICE_MEMORY = 2,
        NVML_MEMORY_LOCATION_REGISTER_FILE = 3,
        NVML_MEMORY_LOCATION_TEXTURE_MEMORY = 4,
        NVML_MEMORY_LOCATION_TEXTURE_SHM = 5,
        NVML_MEMORY_LOCATION_CBU = 6,
        NVML_MEMORY_LOCATION_SRAM = 7,
        NVML_MEMORY_LOCATION_COUNT
    }
}